module.exports = {
    emojis: {
        off: ':x:',
        error: ':warning:',
        queue: ':bar_chart:',
        music: ':musical_note:',
        success: ':white_check_mark:',
        room: ':house_with_garden:',
        search: ':mag:',
        loading:':hourglass_flowing_sand:',
        door: ':door:',
        volume_0: ':speaker:',
        volume_1: ':sound:',
        volume_2: ':loud_sound:',
        outbox: ':outbox_tray:',
        inbox: ':inbox_tray:',
        bear: ':teddy_bear:',
        relax_face: ':relaxed:',
        figure_down: ':point_down:',
        duration: ':tickets:',
        request: ':envelope_with_arrow:',
        bot: ':snowman:',
        guitar: ':guitar:',
        control_knobs: ':control_knobs:',
        diamond: ':gem:',
    },

    discord: {
        token: '',
        prefix: 'm/',
        activity: 'TYPE | m!help |',
        botname: 'มิกุ',
		username: '✨ M i K U 🎧#1031',
		clientId: '884786761635627150',
		permission: '140164582464',
    },
	
    filters: ['8D', 'gate', 'haas', 'phaser', 'treble', 'tremolo', 'vibrato', 'reverse', 'karaoke', 'flanger', 'mcompand', 'pulsator', 'subboost', 'bassboost', 'vaporwave', 'nightcore', 'normalizer', 'surrounding'],
};
